In [1]:
class math():
    def __init__():               # withou self there is no constructor
        print("hello")

In [2]:
o=math
o.__init__()

hello


In [5]:
class math():
    def __init__(self,a,b): # withou self there is no constructor
        self.a=a
        self.b=b
        print(a,b)
        print("hello")

In [6]:
o=math(2,3)

2 3
hello


# inheritence

In [7]:
# single level inheritence(one parent and one child)
class ClassA():
    a,b=20,30
    def display():
        print("i am from class A")
class ClassB():
    c,d=22,33
    def show():
        print("i am from class B")

In [17]:
obj=ClassA
print(obj.a)
print(obj.b)
obj.display()
print(obj.c)
print(obj.d)
obj.show()

20
30
i am from class A


AttributeError: type object 'ClassA' has no attribute 'c'

In [14]:
class ClassA():
    a,b=20,30
    def display():
        print("i am from class A")
class ClassB(ClassA):
    c,d=22,33
    def show():
        print("i am from class B")

In [18]:
obj=ClassB
print(obj.a)
print(obj.b)
obj.display()
print(obj.c)
print(obj.d)
obj.show()

20
30
i am from class A
22
33
i am from class B


In [21]:
#multi level inheritent(one parent 2 child)
class ClassA():
     def classa():
        print("i am from class A")
class ClassB(ClassA):
    def classb():
        print("i am from class B")
class ClassC(ClassB):
    def classc():
        print("i am from class B")


In [22]:
ob=ClassC
ob.classa()
ob.classb()
ob.classc()

i am from class A
i am from class B
i am from class B


In [27]:
#multiple level inheritence(more parents and 1 child)
class ClassA():
     def classa():
        print("i am from class A")
class ClassB():
    def classb():
        print("i am from class B")
class ClassC(ClassA,ClassB):
    def classc():
        print("i am from class B")


In [26]:
ob1=ClassC
ob1.classa()
ob1.classb()
ob1.classc()

i am from class A
i am from class B
i am from class B


# packages modules using oop's concept

In [ ]:
#modules:(.py file)
-group of functions and classes
#packages(folder)
-collection of modules

In [28]:
from packages.programs import *
obj=calsi
print(obj.add(2,5))
print(obj.sub(2,6))
print(obj.mul(2,3))
print(obj.div(2,5))
print(obj.mod(5,6))

7
-4
6
0.4
5


In [1]:
from packages.programs import math
obj1=math
print(obj1.power(2,5))
print(obj1.IsEven(6))
print(obj1.IsOdd(3))

IndentationError: unindent does not match any outer indentation level (programs.py, line 28)

In [ ]:
#python libraries for datascience
#datascience:
-organising,processing,analizing the hug ammount of data.
-apply data visualization
-extracting thr data from the source.
-nearly 20 python libraries for datascience
#top 3
-numpy
-pandas
-matplotlib

In [ ]:
#numpy(numerical python)
-it is a fundamental package for scientific computing in python.
-numpy is a python library
-it is used to creat multidimebtional arrays for fast operations.
-for installing numpy-------->pip install numpy
-use the following import converasation to access numpy library
    -import numpy as np

In [3]:
#1 dimension array
import numpy as np
array1d=np.array([1,3,5,4,2,5])
print(array1d)
print(type(array1d))

[1 3 5 4 2 5]
<class 'numpy.ndarray'>


In [10]:
#2 dimension array
import numpy as np
array2d=np.array([[1,3,5],[4,2,5]])
print(array2d)
print(type(array2d))
array2d

[[1 3 5]
 [4 2 5]]
<class 'numpy.ndarray'>


array([[1, 3, 5],
       [4, 2, 5]])

In [ ]:
import numpy as np
array2d=np.array([[1,3,5],[4,2,5]])
print(array2d)
print(type(array2d))

In [11]:
import numpy as np
li=[2,3,4,'f','l']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))
a1

<class 'list'>
['2' '3' '4' 'f' 'l']
<class 'numpy.ndarray'>


array(['2', '3', '4', 'f', 'l'], dtype='<U11')

In [12]:
#using arange() function
import numpy as np
a=np.arange(15)
print(a)
print(type(a))
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
#using reshape(row,columns)
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
print(type(a))
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
import numpy as np
a=np.arange(15).reshape(5,3)
print(a)
print(type(a))
a

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
<class 'numpy.ndarray'>


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
# array size is too large print be  like this
import numpy as np
a=np.arange(10000)
print(a)
print(type(a))
a

[   0    1    2 ... 9997 9998 9999]
<class 'numpy.ndarray'>


array([   0,    1,    2, ..., 9997, 9998, 9999])

In [20]:
import numpy as np
a=np.arange(10000).reshape(100,100)
print(a)
print(type(a))
a

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
<class 'numpy.ndarray'>


array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [21]:
import numpy as np
a=np.arange(10000).reshape(50,200)
print(a)
print(type(a))
a

[[   0    1    2 ...  197  198  199]
 [ 200  201  202 ...  397  398  399]
 [ 400  401  402 ...  597  598  599]
 ...
 [9400 9401 9402 ... 9597 9598 9599]
 [9600 9601 9602 ... 9797 9798 9799]
 [9800 9801 9802 ... 9997 9998 9999]]
<class 'numpy.ndarray'>


array([[   0,    1,    2, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  397,  398,  399],
       [ 400,  401,  402, ...,  597,  598,  599],
       ...,
       [9400, 9401, 9402, ..., 9597, 9598, 9599],
       [9600, 9601, 9602, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9997, 9998, 9999]])

In [22]:
import numpy as np
a=np.arange(10000).reshape(10000,1)
print(a)
print(type(a))
a

[[   0]
 [   1]
 [   2]
 ...
 [9997]
 [9998]
 [9999]]
<class 'numpy.ndarray'>


array([[   0],
       [   1],
       [   2],
       ...,
       [9997],
       [9998],
       [9999]])