# numpy (continue)

In [1]:
import numpy as np
np.__version__

'1.18.1'

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1.23,2,3,4,5])

array([1.23, 2.  , 3.  , 4.  , 5.  ])

In [4]:
np.array([1,2,3,4,5],dtype='int32')

array([1, 2, 3, 4, 5])

In [5]:
np.array([1,2,3,4,5],dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3,5),56.78)

array([[56.78, 56.78, 56.78, 56.78, 56.78],
       [56.78, 56.78, 56.78, 56.78, 56.78],
       [56.78, 56.78, 56.78, 56.78, 56.78]])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [12]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [13]:
np.random.randint(1,50,size=(4,4))

array([[22, 40, 27, 45],
       [29, 18, 34,  9],
       [16, 46, 47, 11],
       [45, 31,  9, 27]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
d=np.array([2,3,4,6])
np.diag(d)

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [16]:
d=np.array([2,3,4,6]*3)
d           

array([2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6])

In [17]:
d=np.repeat([2,3,4,6],3)
d     

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 6, 6, 6])

In [18]:
a=np.array([2,3,4])
b=np.array([5,5,5])
a+b

array([7, 8, 9])

In [19]:
a*3

array([ 6,  9, 12])

In [20]:
# nd array---->no of dimensions
1)ndarray
2)ndarray.shap()
3)ndarray.datype()
4)ndarray.size()
5)ndarray.itemsize

SyntaxError: invalid syntax (<ipython-input-20-f84c35668f8a>, line 2)

In [38]:
a=np.array([1,2,3],[2,3,4])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

TypeError: data type not understood

In [37]:
a[::-1]

[[4, 5, 6], [1, 2, 3]]

In [36]:
n1=np.arange(1,5).reshape(2,2)
n2=np.arange(5,9).reshape(2,2)
print(n1)
print(n2)
print(n1)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]]


In [35]:
print(n1)
print(n2)
print(n1.dot(n2))

NameError: name 'n1' is not defined

In [34]:
x=np.array([1,2,3,4,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [33]:
a=([[1,2,3],[4,5,6]])
print(a)
print(a.max())
print(a.min())
print(a.sum())
print(a.sqrt(a))
print(a.sin(a))
print(a.cos(a))
print(a.log(a))

[[1, 2, 3], [4, 5, 6]]


AttributeError: 'list' object has no attribute 'max'

In [32]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.max(axis=0))
print(a.max(axis=1))

[[1 2 3]
 [4 5 6]]
[4 5 6]
[3 6]


In [31]:
a=np.array([2,3,4,5,1])
print(a[0])
print(a[3])

2
5


In [30]:
a<3

array([[ True,  True, False],
       [False, False, False]])

In [29]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [28]:
print(a[0])
print(a[1])

2
3


In [27]:
b=np.array(3)
a=np.array(3)[:,np.newaxis]
c=a+b
print(b)
print(a)
print(a[0])

IndexError: too many indices for array

In [26]:
print(c)

NameError: name 'c' is not defined

In [24]:
print(c)
print(c[2][2])
c[0]

NameError: name 'c' is not defined

In [25]:
print(c)
print(c[2][2])
print(c[0])

NameError: name 'c' is not defined

In [23]:
n=np.ones((3,3))
np.vstack((n,np.array((2,2,2))))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [22]:
n=np.ones((3,3))
print(n)
np.vstack((n,np.array((2,2,2))))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [21]:
n=np.ones((3,3))
b=np.array((2,2,2)).reshape(3,1)
print(n)
print(b)
np.hstack((n,b))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2]
 [2]
 [2]]


array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [ ]:
# pandas:
-it is an open source python librry that produces high performance
-load,prepare,manipulate,model,analyze
-pandas basically use for data analysis.
-data cleaning
-data transformation
-data analysis
#panda notations
1)panda series
2)panda dataframes

In [ ]:
#datastructures in python pandas:
1)series
-creating a pandas series
-indexing series
2) data frame(default table format)


In [ ]:
pip install pandas

In [ ]:
#1)pandas series


In [41]:
import pandas as pd
a=pd.Series([1,2,3,4,5])
print(a)
print(type(a))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [42]:
import pandas as pd
c=pd.Series(['ramya','rollins','reigns'])
print(c)
print(type(c))

0      ramya
1    rollins
2     reigns
dtype: object
<class 'pandas.core.series.Series'>


In [43]:
import pandas as pd
c=pd.Series(['ramya','rollins','reigns',1,2,3,4,5.78])
print(c)
print(type(c))

0      ramya
1    rollins
2     reigns
3          1
4          2
5          3
6          4
7       5.78
dtype: object
<class 'pandas.core.series.Series'>


In [44]:
print([c[0]])
print(c[5])

['ramya']
3


In [45]:
print(c[::-1])

7       5.78
6          4
5          3
4          2
3          1
2     reigns
1    rollins
0      ramya
dtype: object


In [46]:
print(a[-5:-1])

0    1
1    2
2    3
3    4
dtype: int64


In [47]:
c

0      ramya
1    rollins
2     reigns
3          1
4          2
5          3
6          4
7       5.78
dtype: object

In [48]:
import pandas as pd
a=pd.Series([1,2,3],index=(['a','b','c']))
print(a)

a    1
b    2
c    3
dtype: int64


In [50]:
import pandas as pd
a=pd.Series([1,2,3],index=pd.date_range('22-11-2020','24-11-2020'))
print(a)

2020-11-22    1
2020-11-23    2
2020-11-24    3
Freq: D, dtype: int64
