In [ ]:
#pandas
-series
-dataframes

In [ ]:
#  panda series:

In [1]:
import pandas as pd
pd.__version__

'1.0.1'

In [3]:
s="hello"
pd.Series(s)

0    hello
dtype: object

In [4]:
s1=input().split()
pd.Series(s1)

ramya reigns rollins


0      ramya
1     reigns
2    rollins
dtype: object

In [5]:
l=[23,'abc',89.78]
pd.Series(l)

0       23
1      abc
2    89.78
dtype: object

In [6]:
t=(23,24,25,67,89)
pd.Series(t)

0    23
1    24
2    25
3    67
4    89
dtype: int64

In [7]:
d={'cource':'python','org':'apssdc','training':'online'}
pd.Series(d)

cource      python
org         apssdc
training    online
dtype: object

In [8]:
import numpy as np
a=np.arange(4,10)
pd.Series(a)

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int32

In [10]:
r=np.random.randint(2,20,10)
pd.Series(r)

0     9
1     5
2     6
3    12
4     6
5     8
6    18
7    12
8    14
9    13
dtype: int32

In [14]:
print(r[5])
print(r[::-1])
print(r[:4])
print(r[::2])

8
[13 14 12 18  8  6 12  6  5  9]
[ 9  5  6 12]
[ 9  6  6 18 14]


In [17]:
n=int(input("enter a num:"))
l={i:i**2 for i in range(1,n+1)}
pd.Series(l)

enter a num:10


1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
dtype: int64

In [20]:
a=pd.Series(np.arange(0,15)**2,index=range(0,15))
print(a)

0       0
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
11    121
12    144
13    169
14    196
dtype: int32


In [21]:
n=int(input("enter a num:"))
l={i:i**2 for i in range(1,n+1)}
pd.Series(l)

enter a num:5


1     1
2     4
3     9
4    16
5    25
dtype: int64

In [ ]:
# data frames:
-(default table format)
-2d labeled array
-there are mostly used in dataanalysis.

In [25]:
import pandas as pd
n=input().split()
pd.DataFrame(n)

python workshop


0
0    python
1  workshop

In [27]:
d=[['ramya','ece'],['reigns','civil'],['rollins','cse']]
pd.DataFrame(d)

0      1
0    ramya    ece
1   reigns  civil
2  rollins    cse

In [28]:
d=[['ramya','ece'],['reigns','civil'],['rollins','cse']]
pd.DataFrame(d,columns=['name','branch'])

name branch
0    ramya    ece
1   reigns  civil
2  rollins    cse

In [29]:
d=[['ramya','ece'],['reigns','civil'],['rollins','cse']]
pd.DataFrame(d,index=['one','two','three'],columns=['name','branch'])

name branch
one      ramya    ece
two     reigns  civil
three  rollins    cse

In [30]:
d=[[1,2,3],[4,5,6]]
pd.DataFrame(d)

0  1  2
0  1  2  3
1  4  5  6

In [31]:
d=[[1,2,3],[4,5,6]]
pd.DataFrame(d,columns=['1st','2nd','3rd'])

1st  2nd  3rd
0    1    2    3
1    4    5    6

In [33]:
d1={'Name':'Ramya','Org':'Apssdc','Training':'Python'}
pd.DataFrame(d1,index=[1])

Name     Org Training
1  Ramya  Apssdc   Python

In [35]:
d2={'College':'aditya','Branch':'ece'}
pd.DataFrame(d1,d2)

Name     Org Training
College  Ramya  Apssdc   Python
Branch   Ramya  Apssdc   Python

In [37]:
d3={'python':'workshop','Online':'workshop'}
pd.DataFrame(d1,d2,d3)

python Online
College    NaN    NaN
Branch     NaN    NaN

In [38]:
d2={'College':'aditya','Branch':'ece','hello':'everyone'}
pd.DataFrame(d1,d2)

Name     Org Training
College  Ramya  Apssdc   Python
Branch   Ramya  Apssdc   Python
hello    Ramya  Apssdc   Python

In [40]:
d2={'College':'aditya','Branch':'ece','30-07-2020':'day-16'}
pd.DataFrame(d1,d2,d3)

python Online
College       NaN    NaN
Branch        NaN    NaN
30-07-2020    NaN    NaN

In [42]:
d3={'python':'workshop','Online':'workshop','30-07-2020':'day-16'}
pd.DataFrame(d1,d2,d3)

python Online 30-07-2020
College       NaN    NaN        NaN
Branch        NaN    NaN        NaN
30-07-2020    NaN    NaN        NaN

In [43]:
a={'Name':'Ramya','Org':'Apssdc','Training':'Python'}
b=pd.DataFrame(a)
c={'College':'aditya','Branch':'ece','hello':'everyone'}
d=pd.DataFrame(c)
print(b,'\n''\n',d)

ValueError: If using all scalar values, you must pass an index

In [46]:
a={'python':32,'c':18,'java':20}
b=pd.Series(a)
c={'python':23,'java':23}
d=pd.Series(c)
print(b,'\n''\n',d)

python    32
c         18
java      20
dtype: int64 

 python    23
java      23
dtype: int64


In [47]:
final={'mid1':b,'mid2':d}
pd.DataFrame(final)

mid1  mid2
c         18   NaN
java      20  23.0
python    32  23.0

In [ ]:
={'python':32,'c':18,'java':20}
b=pd.Series(a)
c={'python':23,'java':23}
d=pd.Series(c)
print(b,'\n''\n',d)

In [ ]:
final{'mid1':b,'mid2':d}
pd.DataFrame(final)

In [44]:
d=pd.DataFrame({'name':['ramya','rollins'],'age':[23,24],'branch':['ece','civil']})
print(d)

      name  age branch
0    ramya   23    ece
1  rollins   24  civil


In [48]:
import pandas as pd
t1={'Name':'Ramya','Org':'Apssdc','Training':'Python'}
t2={'Name':'Rollins','Org':'Apssdc'}
t3={'Name':'Reigns','Org':'Apssdc','Training':'Python'}
a=pd.DataFrame([t1,t2,t3],columns=['Name','Org','Training'])
a

Name     Org Training
0    Ramya  Apssdc   Python
1  Rollins  Apssdc      NaN
2   Reigns  Apssdc   Python

In [50]:
import pandas as pd
t1={'Name':'Ramya','Org':'Apssdc','Training':'Python'}
t2={'Name':'Rollins','Org':'Apssdc'}
t3={'Name':'Reigns','Org':'Apssdc','Training':'Python'}
a=pd.DataFrame([t1,t2,t3],index=['Name','Org','Training'])
b=pd.DataFrame([t1,t2,t3],columns=['Name','Org'])
c=pd.DataFrame([t1,t2,t3],columns=['Name','Org','Training'])
print(a)

             Name     Org Training
Name        Ramya  Apssdc   Python
Org       Rollins  Apssdc      NaN
Training   Reigns  Apssdc   Python


In [51]:
print(b)

      Name     Org
0    Ramya  Apssdc
1  Rollins  Apssdc
2   Reigns  Apssdc


In [52]:
print(c)

      Name     Org Training
0    Ramya  Apssdc   Python
1  Rollins  Apssdc      NaN
2   Reigns  Apssdc   Python


In [53]:
a

Name     Org Training
Name        Ramya  Apssdc   Python
Org       Rollins  Apssdc      NaN
Training   Reigns  Apssdc   Python

In [54]:
a.loc['Org']

Name        Rollins
Org          Apssdc
Training        NaN
Name: Org, dtype: object

In [55]:
a.loc['Name']

Name         Ramya
Org         Apssdc
Training    Python
Name: Name, dtype: object

In [56]:
a.iloc[2]

Name        Reigns
Org         Apssdc
Training    Python
Name: Training, dtype: object

In [57]:
a.iloc[1]

Name        Rollins
Org          Apssdc
Training        NaN
Name: Org, dtype: object

In [58]:
a['branch']='ECE'
a

Name     Org Training branch
Name        Ramya  Apssdc   Python    ECE
Org       Rollins  Apssdc      NaN    ECE
Training   Reigns  Apssdc   Python    ECE

In [59]:
a.T

Name      Org Training
Name       Ramya  Rollins   Reigns
Org       Apssdc   Apssdc   Apssdc
Training  Python      NaN   Python
branch       ECE      ECE      ECE

In [62]:
a.T.loc['Org']

Name        Apssdc
Org         Apssdc
Training    Apssdc
Name: Org, dtype: object

In [64]:
a.T.iloc[3]

Name        ECE
Org         ECE
Training    ECE
Name: branch, dtype: object

In [67]:
a={'python':32,'c':18,'java':20}
b=pd.Series(a)
c={'python':23,'c':18,'java':23}
d=pd.Series(c)
print(b,'\n''\n',d)

python    32
c         18
java      20
dtype: int64 

 python    23
c         18
java      23
dtype: int64


In [68]:
final={'mid1':b,'mid2':d}
pd.DataFrame(final)

mid1  mid2
python    32    23
c         18    18
java      20    23

In [70]:
d1=pd.DataFrame({'num':[1,2,3,4],'age':[50,45,67,79]},index=[2002,2003,2004,2005])
d1

num  age
2002    1   50
2003    2   45
2004    3   67
2005    4   79

In [72]:
d2=pd.DataFrame({'num1':[1,2,3,4],'age1':[50,45,67,79]},index=[2002,2003,2004,2005])
d2

num1  age1
2002     1    50
2003     2    45
2004     3    67
2005     4    79

In [73]:
d1.join(d2)

num  age  num1  age1
2002    1   50     1    50
2003    2   45     2    45
2004    3   67     3    67
2005    4   79     4    79

In [74]:
d2.join(d1)

num1  age1  num  age
2002     1    50    1   50
2003     2    45    2   45
2004     3    67    3   67
2005     4    79    4   79

In [87]:
d3=pd.DataFrame({'weight':[10,20,30,40],'age':[50,45,67,79]},index=[2002,2003,2004,2005])
d4=pd.DataFrame({'weight':[10,20,30,40],'age':[500,450,670,790]},index=[2012,2013,2014,2015])
d3

weight  age
2002      10   50
2003      20   45
2004      30   67
2005      40   79

In [86]:
d3=pd.DataFrame({'weight':[10,20,30,40],'age':[5,45,67,79]},index=[2002,2003,2004,2005])
d4=pd.DataFrame({'weight':[10,20,30,40],'age':[500,450,670,790]},index=[2012,2013,2014,2015])
d4

weight  age
2012      10  500
2013      20  450
2014      30  670
2015      40  790

In [88]:
d3.merge(d4)c=pd.contact([d3,d4])

Empty DataFrame
Columns: [weight, age]
Index: []

In [89]:
d3.merge(d4,on='weight')

weight  age_x  age_y
0      10     50    500
1      20     45    450
2      30     67    670
3      40     79    790

In [91]:
c=pd.concat([d3,d4])
c

weight  age
2002      10   50
2003      20   45
2004      30   67
2005      40   79
2012      10  500
2013      20  450
2014      30  670
2015      40  790

In [92]:
d=pd.date_range('2020-11-12',periods=5)
d

DatetimeIndex(['2020-11-12', '2020-11-13', '2020-11-14', '2020-11-15',
               '2020-11-16'],
              dtype='datetime64[ns]', freq='D')

In [96]:
d1=pd.date_range('2020-01-11','2020-01-20')
pd.Series(d1)

0   2020-01-11
1   2020-01-12
2   2020-01-13
3   2020-01-14
4   2020-01-15
5   2020-01-16
6   2020-01-17
7   2020-01-18
8   2020-01-19
9   2020-01-20
dtype: datetime64[ns]